In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer

a. Rescaling: Normalised the dataset using MinMaxScaler class

In [4]:
df = pd.read_csv('winequality-red.csv')

X = df.drop(columns=['quality'])
min_max_scaler = MinMaxScaler()
X_rescaled = min_max_scaler.fit_transform(X)
print("Rescaled Data (MinMaxScaler):")
X_rescaled

Rescaled Data (MinMaxScaler):


array([[0.24778761, 0.39726027, 0.        , ..., 0.60629921, 0.13772455,
        0.15384615],
       [0.28318584, 0.52054795, 0.        , ..., 0.36220472, 0.20958084,
        0.21538462],
       [0.28318584, 0.43835616, 0.04      , ..., 0.40944882, 0.19161677,
        0.21538462],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.53543307, 0.25149701,
        0.4       ],
       [0.11504425, 0.35958904, 0.12      , ..., 0.65354331, 0.22754491,
        0.27692308],
       [0.12389381, 0.13013699, 0.47      , ..., 0.51181102, 0.19760479,
        0.4       ]])

b. Standardizing Data (transform them into a standard Gaussian distribution with a mean of 0 and
a standard deviation of 1)

In [5]:
standard_scaler = StandardScaler()
X_standardized = standard_scaler.fit_transform(X)

print("\nStandardized Data (StandardScaler):")
X_standardized


Standardized Data (StandardScaler):


array([[-0.52835961,  0.96187667, -1.39147228, ...,  1.28864292,
        -0.57920652, -0.96024611],
       [-0.29854743,  1.96744245, -1.39147228, ..., -0.7199333 ,
         0.1289504 , -0.58477711],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.33117661,
        -0.04808883, -0.58477711],
       ...,
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.70550789,
         0.54204194,  0.54162988],
       [-1.39015528,  0.65462046, -0.77526673, ...,  1.6773996 ,
         0.30598963, -0.20930812],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.51112954,
         0.01092425,  0.54162988]])

c. Normalizing Data ( rescale each observation to a length of 1 (a unit norm). For this, use the
Normalizer class.)

In [6]:
normalizer = Normalizer()
X_normalized = normalizer.fit_transform(X)

print("\nNormalized Data (Normalizer):")
X_normalized


Normalized Data (Normalizer):


array([[0.19515252, 0.01846037, 0.        , ..., 0.09256559, 0.0147683 ,
        0.24789644],
       [0.10724124, 0.01209901, 0.        , ..., 0.04399641, 0.00934924,
        0.134739  ],
       [0.13545665, 0.01319834, 0.00069465, ..., 0.05661393, 0.01128805,
        0.17018912],
       ...,
       [0.12306863, 0.0099627 , 0.00253951, ..., 0.06680869, 0.01465103,
        0.21488174],
       [0.10566885, 0.01155193, 0.0021492 , ..., 0.06393861, 0.01271608,
        0.18268174],
       [0.12589937, 0.0065048 , 0.00986212, ..., 0.07113314, 0.01384893,
        0.2308155 ]])